name: Release to NuGet

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Version
      id: version
      uses: PaulHatch/semantic-version@v5.3.0
      with:
        tag_prefix: ""
        version_from_branch: true
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build -c Release -p:Version=${VERSION}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        VERSION: ${{ steps.version.outputs.version }}.${{ steps.version.outputs.increment }}
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack nugets
      run: dotnet pack -p:PackageVersion=${PACKAGE_VERSION} -c Release --no-build --output .
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        PACKAGE_VERSION: ${{ steps.version.outputs.version }}

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
